# Generated by Django 5.2.14 on 2026-07-14 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MNGTournament', '0002_player_user_match'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('finalPosition', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'teams_tournaments',
            },
        ),
        migrations.AddField(
            model_name='team',
            name='captain',
            field=models.ForeignKey(db_column='captain_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='captained_teams', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='inviteCode',
            field=models.CharField(blank=True, default='', max_length=6, null=True),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['inviteCode'], name='idx_tea_invite_code'),
        ),
        migrations.AddField(
            model_name='teamtournament',
            name='team',
            field=models.ForeignKey(db_column='teams_id', on_delete=django.db.models.deletion.CASCADE, related_name='tournament_registrations', to='MNGTournament.team'),
        ),
        migrations.AddField(
            model_name='teamtournament',
            name='tournament',
            field=models.ForeignKey(db_column='tournaments_id', on_delete=django.db.models.deletion.CASCADE, related_name='team_registrations', to='MNGTournament.tournament'),
        ),
        migrations.AddIndex(
            model_name='teamtournament',
            index=models.Index(fields=['team'], name='idx_tt_teamsId'),
        ),
        migrations.AddIndex(
            model_name='teamtournament',
            index=models.Index(fields=['tournament'], name='idx_tt_tournamentsId'),
        ),
        migrations.AddIndex(
            model_name='teamtournament',
            index=models.Index(fields=['-score'], name='idx_tt_score'),
        ),
        migrations.AddIndex(
            model_name='teamtournament',
            index=models.Index(fields=['finalPosition'], name='idx_tt_finalPosition'),
        ),
        migrations.AddIndex(
            model_name='teamtournament',
            index=models.Index(fields=['status'], name='idx_tt_status'),
        ),
        migrations.AddConstraint(
            model_name='teamtournament',
            constraint=models.UniqueConstraint(fields=('team', 'tournament'), name='uq_team_tournament'),
        ),
    ]
